import {beforeAll,afterAll,it,expect,describe} from 'vitest'
import {readFileSync} from 'node:fs'
import {initializeTestEnvironment,assertFails,type RulesTestEnvironment} from '@firebase/rules-unit-testing'
import {doc,setDoc,getDoc,updateDoc,deleteDoc,type Firestore} from 'firebase/firestore'
import {salvarGestaoNuvem,carregarGestaoNuvem,salvarUsoNuvem} from '../../src/data/gestao'
import {prepararExclusao,executarExclusao} from '../../src/data/gestao-exclusao'
import {gravarNuvem,carregarNuvem} from '../../src/data/nuvem'
import {registrarOcorrencia,type EstadoTreino} from '../../src/app/treino'
import {ocorrenciaBase} from '../auxiliares-agregado'
describe.skipIf(!process.env.FIRESTORE_EMULATOR_HOST)('P08 regras/concorrência/exclusão em emulador',()=>{
 let env:RulesTestEnvironment
 const contexto=(usuario='campo')=>({projetoId:'p1',usuario,nome:'Teste',papel:usuario==='coord'?'coordenacao' as const:usuario==='consulta'?'consulta' as const:'campo' as const,revisaoServidor:0})
 const banco=(u='campo')=>(env.authenticatedContext(u).firestore() as unknown as {_delegate:Firestore})._delegate
 const entrada={ano:2026,numero:'',previsao_eclosao:null,antecedencia_dias:7,nota_previsao:null}
 beforeAll(async()=>{const host=process.env.FIRESTORE_EMULATOR_HOST!;if(!/^127\.0\.0\.1:\d+$/.test(host))throw new Error('Só emulador local');env=await initializeTestEnvironment({projectId:'demo-gestao',firestore:{host:'127.0.0.1',port:Number(host.split(':')[1]),rules:readFileSync('firestore.rules','utf8')}});await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,'projetos/p1'),{nome:'Teste',ativo:true,revisao_dados:0,ultima_operacao:null});for(const u of ['campo','coord','consulta'])await setDoc(doc(db,`projetos/p1/membros/${u}`),{uid:u,projeto_id:'p1',ativo:true,papel:contexto(u).papel})});let i=0;for(let k=0;k<3;k++){const base=k?await carregarNuvem(contexto(),banco()):{schema:1,revisao:0,operacoes:[],ocorrencias:[],ninhos:[],transferencias:[],aberturas:[],visitas:[],contexto:contexto()} as EstadoTreino;const novo=registrarOcorrencia(base,{...ocorrenciaBase,numeroRegistro:null},'I',{usuario:'campo',instante:'2026-10-03T12:00:00Z',novoId:()=>`n-${++i}`});await gravarNuvem(base,novo,banco())}},30000)
 afterAll(async()=>{await env?.cleanup()})
 it('duas reservas concorrentes no mesmo ano recebem 001/002; outro ano reinicia 001',async()=>{const ids=(await carregarNuvem(contexto(),banco())).ninhos.map(n=>n.id);const dois=await Promise.all(ids.slice(0,2).map(id=>salvarGestaoNuvem(contexto(),id,entrada,null,banco())));expect(dois.map(n=>n.numero).sort()).toEqual(['001','002']);const outro=await salvarGestaoNuvem(contexto(),ids[2]!,{...entrada,ano:2027},null,banco());expect(outro.numero).toBe('001');expect(Object.keys((await carregarGestaoNuvem(contexto(),banco())).ninhos)).toHaveLength(3)},20000)
 it('versão antiga, número duplicado, não membro/consulta e escrita sem reserva são bloqueados',async()=>{const g=await carregarGestaoNuvem(contexto(),banco()),n=Object.values(g.ninhos).find(n=>n.ano===2026)!,outro=Object.values(g.ninhos).find(x=>x.ano===2026&&x.id!==n.id)!;await expect(salvarGestaoNuvem(contexto(),n.id,entrada,null,banco())).rejects.toThrow('outro aparelho');await expect(salvarGestaoNuvem(contexto(),n.id,{...entrada,numero:outro.numero},n.versao,banco())).rejects.toThrow('reservado');await expect(salvarGestaoNuvem(contexto('consulta'),n.id,entrada,n.versao,banco('consulta'))).rejects.toThrow();await assertFails(getDoc(doc(banco('intruso'),`projetos/p1/gestao/${n.id}`)));await assertFails(updateDoc(doc(banco(),`projetos/p1/gestao/${n.id}`),{numero:'099'}));await assertFails(deleteDoc(doc(banco('coord'),`projetos/p1/ninhos/${n.id}`)))})
 it('medição é somente coordenação e não permite autoelevação',async()=>{await expect(salvarUsoNuvem(contexto(),800,'2026-10-03',null,banco())).rejects.toThrow();await salvarUsoNuvem(contexto('coord'),820,'2026-10-03',null,banco('coord'));await assertFails(updateDoc(doc(banco(),'projetos/p1/membros/campo'),{papel:'coordenacao'}))})
 it('exclusão exige coordenação e hashes; remove a seleção com recibo, preserva outro ano e reservas',async()=>{await expect(prepararExclusao(contexto(),{modo:'ano',ano:'2026',inicio:'',fim:''},banco())).rejects.toThrow('coordenação');const c=contexto('coord'),db=banco('coord');let p=await prepararExclusao(c,{modo:'ano',ano:'2026',inicio:'',fim:''},db);expect(p.grupos).toHaveLength(2);await expect(executarExclusao({...c,usuario:'campo'},p,'a'.repeat(64),'b'.repeat(64),'Papel falso',()=>{},banco())).rejects.toBeDefined();await expect(executarExclusao(c,p,'','','teste',()=>{},db)).rejects.toThrow('inválidos');expect((await carregarNuvem(c,db)).ninhos).toHaveLength(3);const meta=await carregarGestaoNuvem(c,db),m=Object.values(meta.ninhos).find(n=>n.ano===2026)!;await salvarGestaoNuvem(c,m.id,{...entrada,numero:m.numero,antecedencia_dias:8},m.versao,db);await expect(executarExclusao(c,p,'a'.repeat(64),'b'.repeat(64),'Backup desatualizado',()=>{},db)).rejects.toThrow('mudou');p=await prepararExclusao(c,{modo:'ano',ano:'2026',inicio:'',fim:''},db);const n=await executarExclusao(c,p,'a'.repeat(64),'b'.repeat(64),'Retenção fictícia',()=>{},db);expect(n).toBe(2);expect((await carregarNuvem(c,db)).ninhos).toHaveLength(1);expect((await getDoc(doc(db,'projetos/p1/gestao_numeros/2026-001'))).exists()).toBe(true);await expect(executarExclusao(c,p,'a'.repeat(64),'b'.repeat(64),'Reuso',()=>{},db)).rejects.toThrow('mudou')},20000)
})
