import {useState} from 'react'
import type {EstadoTreino} from '../../app/treino'
import type {EstadoGestao} from '../../data/gestao'
import {salvarUsoNuvem} from '../../data/gestao'
import {indicadorArmazenamento,diaDoAparelho} from '../../domain/gestao'
import {prepararExclusao,executarExclusao,sha256,type PlanoExclusao} from '../../data/gestao-exclusao'
import {gerarPDF} from '../../report/pdf'
import {copiaCompletaProjeto} from '../../app/nuvem'
function baixar(b:Uint8Array,mime:string,nome:string){const u=URL.createObjectURL(new Blob([new Uint8Array(b)],{type:mime})),a=document.createElement('a');a.href=u;a.download=nome;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export default function Armazenamento({estado,gestao,atualizar}:{estado:EstadoTreino;gestao:EstadoGestao;atualizar:()=>Promise<void>}){
 const c=estado.contexto,coord=c?.papel==='coordenacao',indicador=indicadorArmazenamento(gestao.config)
 const [uso,setUso]=useState(''),[medido,setMedido]=useState(diaDoAparelho()),[erro,setErro]=useState(''),[mensagem,setMensagem]=useState(''),[ocupado,setOcupado]=useState(false)
 const [modo,setModo]=useState<'ano'|'periodo'>('ano'),[ano,setAno]=useState(String(new Date().getFullYear())),[inicio,setInicio]=useState(''),[fim,setFim]=useState('')
 const [plano,setPlano]=useState<PlanoExclusao|null>(null),[pdf,setPdf]=useState(''),[json,setJson]=useState(''),[aceite,setAceite]=useState(false),[confirmacao,setConfirmacao]=useState(''),[motivo,setMotivo]=useState('')
 const habilitado=coord&&navigator.onLine&&estado.statusNuvem==='confirmada'&&gestao.confirmada
 function invalidar(){setPlano(null);setPdf('');setJson('');setAceite(false);setConfirmacao('')}
 async function agir(f:()=>Promise<void>){setOcupado(true);setErro('');try{await f()}catch(e){setErro(e instanceof Error?e.message:'Falha na gestão.')}finally{setOcupado(false)}}
 return <section className="cartao"><h2>Armazenamento e preservação</h2><p>Firestore Spark: 1 GiB de armazenamento gratuito. O uso abaixo é uma medição manual do console, incluindo índices; não é a capacidade do aparelho.</p><p>{indicador.percentual===null?'Uso da nuvem não medido.':`${gestao.config!.uso_mib} MiB · ${indicador.percentual.toFixed(1)}% · medição em ${gestao.config!.medido_em}`}</p>{indicador.pertoLimite&&<p className="mensagem aviso">Armazenamento acima de 80% na última medição. Confira o console, preserve backups e planeje a retenção.</p>}<a href="https://console.firebase.google.com/" target="_blank" rel="noreferrer">Consultar Firebase</a>
 {coord&&<form onSubmit={e=>{e.preventDefault();void agir(async()=>{if(!habilitado)throw new Error('Conexão e sincronização confirmadas são necessárias.');await salvarUsoNuvem(c!,Number(uso),medido,gestao.config?.versao??null);await atualizar();setMensagem('Medição registrada.')})}}><fieldset disabled={ocupado}><div className="filtros"><label>Uso conferido no console (MiB)<input required type="number" min="0" step="any" value={uso} onChange={e=>setUso(e.target.value)}/></label><label>Data da medição<input required type="date" value={medido} onChange={e=>setMedido(e.target.value)}/></label></div><button className="btn" disabled={!habilitado}>Salvar medição</button></fieldset></form>}
 <h3>Exclusão por ano ou período</h3><p>Exclusão definitiva somente pela coordenação. Primeiro gere e guarde PDF e JSON. Históricos de auditoria e reservas de números permanecem na nuvem; a remoção não libera todo o espaço associado.</p>{!coord?<p>Seu acesso não possui papel de coordenação. A autorização depende de provisionamento administrativo; não pode ser obtida por esta tela.</p>:<fieldset disabled={ocupado}><div className="filtros"><label>Selecionar por<select value={modo} onChange={e=>{setModo(e.target.value as typeof modo);invalidar()}}><option value="ano">Ano de organização</option><option value="periodo">Data de ocorrência (inclusiva)</option></select></label>{modo==='ano'?<label>Ano<input required type="number" min="1000" max="9999" value={ano} onChange={e=>{setAno(e.target.value);invalidar()}}/></label>:<><label>Início<input type="date" value={inicio} onChange={e=>{setInicio(e.target.value);invalidar()}}/></label><label>Fim<input type="date" value={fim} onChange={e=>{setFim(e.target.value);invalidar()}}/></label></>}</div><p>Por período, ninhos sem data de ocorrência não são excluídos. Ano de organização é separado das datas de campo.</p><button className="btn" disabled={!habilitado} onClick={()=>void agir(async()=>{invalidar();if((await copiaCompletaProjeto(c!)).cache?.pendente)throw new Error('Há pendência local. Sincronize antes de preparar a exclusão.');setPlano(await prepararExclusao(c!,{modo,ano,inicio,fim}));setMensagem('Seleção consultada no servidor. Confira os ninhos antes de baixar os backups.')})}>Preparar seleção e backups</button>
 {plano&&<><h3>{plano.grupos.length} ninhos selecionados</h3><p>{plano.relatorio.registros.map(r=>`${plano.relatorio.organizacao?.[r.ficha.ninho.id]?.ano??'sem ano'} / ${plano.relatorio.organizacao?.[r.ficha.ninho.id]?.numero??r.ficha.ninho.codigoInterno}`).join('; ')||'Nenhum ninho.'}</p><div className="acoes"><button className="btn" onClick={()=>void agir(async()=>{const bytes=await gerarPDF(plano.relatorio);baixar(bytes,'application/pdf','backup-antes-exclusao.pdf');setPdf(await sha256(bytes))})}>Baixar PDF de backup</button><button className="btn" onClick={()=>void agir(async()=>{const bytes=new TextEncoder().encode(JSON.stringify({tipo:'BACKUP_ANTES_EXCLUSAO',plano},null,2));baixar(bytes,'application/json','backup-antes-exclusao.json');setJson(await sha256(bytes))})}>Baixar JSON de backup</button></div><p>O navegador não consegue comprovar que você guardou os downloads. Abra ambos os arquivos e confirme abaixo.</p><label><input type="checkbox" checked={aceite} onChange={e=>setAceite(e.target.checked)}/> Guardei e conferi o PDF e o JSON fora deste aplicativo.</label><label>Motivo da exclusão<input value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><label>Digite EXCLUIR {plano.grupos.length}<input value={confirmacao} onChange={e=>setConfirmacao(e.target.value)}/></label><button className="btn" disabled={!habilitado||!plano.grupos.length||!pdf||!json||!aceite||!motivo.trim()||confirmacao!==`EXCLUIR ${plano.grupos.length}`} onClick={()=>void agir(async()=>{try{if((await copiaCompletaProjeto(c!)).cache?.pendente)throw new Error('Outra aba criou uma pendência. Exclusão bloqueada; confira novamente.');const n=await executarExclusao(c!,plano,pdf,json,motivo,n=>setMensagem(`${n} ninhos removidos. Em andamento…`));setMensagem(`${n} ninhos removidos. Backups e auditoria preservados.`)}finally{invalidar();await atualizar()}})}>Excluir definitivamente a seleção</button></>}
 </fieldset>}{ocupado&&<p role="status">Conferindo operação…</p>}{mensagem&&<p role="status">{mensagem}</p>}{erro&&<p className="mensagem erro" role="alert">{erro}</p>}</section>
}
