import {useState} from 'react'
import {excluirNinhoTreino,type EstadoTreino} from '../../app/treino'
import {copiaCompletaProjeto} from '../../app/nuvem'
import {prepararExclusao,executarExclusao,sha256,type PlanoExclusao} from '../../data/gestao-exclusao'
import {gerarPDF} from '../../report/pdf'
function baixar(bytes:Uint8Array,mime:string,nome:string){const u=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:mime})),a=document.createElement('a');a.href=u;a.download=nome;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export default function ExcluirNinho({estado,ninhoId,rotulo,cancelar,aoSalvar,atualizar}:{estado:EstadoTreino;ninhoId:string;rotulo:string;cancelar:()=>void;aoSalvar:(e:EstadoTreino)=>Promise<void>;atualizar:()=>Promise<void>}){
 const [plano,setPlano]=useState<PlanoExclusao|null>(null),[pdf,setPdf]=useState(''),[json,setJson]=useState(''),[aceite,setAceite]=useState(false),[motivo,setMotivo]=useState(''),[confirmacao,setConfirmacao]=useState(''),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false)
 const c=estado.contexto,permitido=!c||c.papel==='coordenacao',habilitado=permitido&&(!c||navigator.onLine&&estado.statusNuvem==='confirmada')
 async function agir(f:()=>Promise<void>){setOcupado(true);setErro('');try{await f()}catch(e){setErro(e instanceof Error?e.message:'Não foi possível excluir. Confira o estado dos dados.')}finally{setOcupado(false)}}
 return <section className="cartao"><h2>Excluir {rotulo}</h2><p>A exclusão remove este cadastro e seus registros vinculados. Auditoria e reservas permanecem. Guarde os backups antes de confirmar.</p>{!permitido?<p>Seu acesso de campo não pode excluir ninhos. Solicite a exclusão à coordenação.</p>:<fieldset disabled={ocupado}>
 {!habilitado&&<p>Conecte-se e confirme a sincronização antes de excluir.</p>}
 <button type="button" className="btn" disabled={!habilitado} onClick={()=>void agir(async()=>{setPlano(null);setPdf('');setJson('');setAceite(false);if(c){if((await copiaCompletaProjeto(c)).cache?.pendente)throw new Error('Há pendência local. Sincronize antes de preparar o backup.');setPlano(await prepararExclusao(c,{modo:'ninho',ninhoId,ano:'',inicio:'',fim:''}))}else{const bytes=new TextEncoder().encode(JSON.stringify({tipo:'BACKUP_TREINO_ANTES_EXCLUSAO',estado},null,2));baixar(bytes,'application/json','backup-treino-'+ninhoId+'.json');setJson(await sha256(bytes))}})}>1. Preparar backup deste ninho</button>
 {plano&&<div className="acoes"><button type="button" className="btn" onClick={()=>void agir(async()=>{const bytes=await gerarPDF(plano.relatorio);baixar(bytes,'application/pdf','backup-ninho-'+ninhoId+'.pdf');setPdf(await sha256(bytes))})}>Baixar PDF</button><button type="button" className="btn" onClick={()=>void agir(async()=>{const bytes=new TextEncoder().encode(JSON.stringify({tipo:'BACKUP_ANTES_EXCLUSAO',plano},null,2));baixar(bytes,'application/json','backup-ninho-'+ninhoId+'.json');setJson(await sha256(bytes))})}>Baixar JSON</button></div>}
 {json&&(!c||pdf)&&<><p>2. Abra e confira os arquivos baixados. O navegador não comprova que você guardou o backup.</p><label><input type="checkbox" checked={aceite} onChange={e=>setAceite(e.target.checked)}/>Guardei e conferi os backups fora do aplicativo.</label><label>Motivo da exclusão<textarea value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><label>Digite EXCLUIR para confirmar a exclusão de {rotulo}<input value={confirmacao} onChange={e=>setConfirmacao(e.target.value)}/></label><button type="button" className="btn" disabled={!habilitado||!aceite||!motivo.trim()||confirmacao!=='EXCLUIR'} onClick={()=>void agir(async()=>{if(c&&plano){if((await copiaCompletaProjeto(c)).cache?.pendente)throw new Error('Outra aba criou uma pendência. Confira novamente antes de excluir.');await executarExclusao(c,plano,pdf,json,motivo,()=>{});await atualizar();cancelar()}else await aoSalvar(excluirNinhoTreino(estado,ninhoId,motivo,{usuario:'usuario-treino-local',instante:new Date().toISOString(),novoId:()=>crypto.randomUUID()}))})}>3. Excluir definitivamente este ninho</button></>}
 </fieldset>}<button type="button" className="btn" disabled={ocupado} onClick={cancelar}>Cancelar exclusão</button>{erro&&<p className="mensagem erro" role="alert">{erro}</p>}</section>
}
