import { useState } from 'react'
import { salvarGestao } from '../../app/gestao'
import type { EstadoTreino } from '../../app/treino'
import type { EstadoGestao } from '../../data/gestao'
import type { GestaoNinho } from '../../domain/gestao'
export default function OrganizarNinho({estado,id,atual,aoSalvar,cancelar}:{estado:EstadoTreino;id:string;atual?:GestaoNinho|undefined;aoSalvar:(g:EstadoGestao)=>void;cancelar:()=>void}){
 const [ano,setAno]=useState(String(atual?.ano??new Date().getFullYear())),[numero,setNumero]=useState(atual?.numero??'')
 const [previsao,setPrevisao]=useState(atual?.previsao_eclosao??''),[dias,setDias]=useState(String(atual?.antecedencia_dias??7)),[nota,setNota]=useState(atual?.nota_previsao??'')
 const [erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false)
 return <section className="cartao"><h2>Organização anual e previsão da equipe</h2><p>O ano é informado pela equipe e não muda quando a abertura ocorre em outro ano. O número anual é independente do registro científico e do cercado.</p><form onSubmit={e=>{e.preventDefault();setErro('');setOcupado(true);void salvarGestao(estado,id,{ano:Number(ano),numero:numero.trim(),previsao_eclosao:previsao||null,antecedencia_dias:Number(dias),nota_previsao:nota.trim()||null},atual?.versao??null).then(aoSalvar).catch(e=>setErro(e instanceof Error?e.message:'Não foi possível salvar a organização.')).finally(()=>setOcupado(false))}}><fieldset disabled={ocupado}><div className="filtros"><label>Ano de organização<input required type="number" min="1000" max="9999" step="1" value={ano} onChange={e=>setAno(e.target.value)}/></label><label>Número anual do ninho<input value={numero} placeholder="Vazio: reservar próximo número (001…)" onChange={e=>setNumero(e.target.value)}/></label><label>Previsão de eclosão informada pela equipe<input type="date" value={previsao} onChange={e=>setPrevisao(e.target.value)}/></label><label>Avisar quantos dias antes<input required type="number" min="0" max="60" step="1" value={dias} onChange={e=>setDias(e.target.value)}/></label><label>Origem / justificativa da previsão<textarea required={!!previsao} value={nota} onChange={e=>setNota(e.target.value)}/></label></div><p className="ajuda">Nenhum prazo de incubação é presumido. O alerta aparece no aplicativo aberto, com a data do aparelho; não envia mensagens ou notificações em segundo plano. Na nuvem, reservar número exige conexão e cadastro confirmado.</p><div className="acoes"><button className="btn prim" disabled={ocupado}>Salvar organização</button><button type="button" className="btn" onClick={cancelar}>Cancelar</button></div></fieldset>{erro&&<p className="mensagem erro" role="alert">{erro}</p>}</form></section>
}
