import {lerRascunho} from '../../src/features/treino/rascunho'
import {describe,it,expect} from 'vitest'
import {campoDaMensagem,validarCadastro,validarCampos} from '../../src/features/treino/validacaoCadastro'
import {criarTreino,corrigirCadastro,registrarOcorrencia,registrarTransferencia,excluirNinhoTreino,type CorrecaoCadastro,type EstadoTreino} from '../../src/app/treino'
import {prepararGravacao} from '../../src/data/nuvem'
import {montarFichaNinho} from '../../src/domain/agregado'
import {ocorrenciaBase,transferenciaBase} from '../auxiliares-agregado'
let i=0
const m=()=>({usuario:'campo',instante:'2026-10-09T12:00:00Z',novoId:()=>`p15-${++i}`})
const base=():EstadoTreino=>({schema:1,revisao:0,operacoes:[],ocorrencias:[],ninhos:[],transferencias:[],visitas:[],aberturas:[],contexto:{projetoId:'p1',usuario:'campo',nome:'Teste',papel:'campo',revisaoServidor:0}})
const criar=()=>registrarOcorrencia(base(),{...ocorrenciaBase,numeroRegistro:'007'},'I',m())
it('rascunho volta somente para a mesma versão, sem aceitar conteúdo corrompido',()=>{expect(lerRascunho(JSON.stringify({versao:2,valores:{numeroRegistro:'0001'}}),2)).toEqual({numeroRegistro:'0001'});expect(lerRascunho(JSON.stringify({versao:1,valores:{numeroRegistro:'0001'}}),2)).toBeNull();expect(lerRascunho('{',null)).toBeNull()})
describe('cadastro guiado e correção auditada',()=>{
 it('permite cadastro sem transferência e sem data conhecida, sem inventar zero',()=>{const erros=validarCadastro({tipo:'CD',natureza:'REPRODUTIVO',situacao:'I'});expect(erros).toEqual({});const e=registrarOcorrencia(base(),{...ocorrenciaBase,dataOcorrencia:null,noiteReferencia:null},'I',m());expect(e.transferencias).toHaveLength(0);expect(e.ocorrencias[0]!.dataOcorrencia).toBeNull()})
 it('identifica exatamente campos condicionais e coordenadas erradas',()=>{const erros=validarCadastro({tipo:'CD',natureza:'REPRODUTIVO',situacao:'T',flagrante:'true',pesca:'true',latitude:'100',longitude:'-38'});expect(Object.keys(erros)).toEqual(expect.arrayContaining(['tumores','tipoEvidencia','latitude','datum','dataTransferencia','cercadoId','numeroNinhoCercado']));expect(erros.latitude).toContain('90')})
 it('erros vindos do salvamento retornam ao campo oficial, sem confundir falta de rede com preenchimento',()=>{expect(campoDaMensagem('DATA_OCORR: a data está depois da abertura.')).toBe('dataOcorrencia');expect(campoDaMensagem('N_REGISTRO: Número já reservado.')).toBe('numeroRegistro');expect(campoDaMensagem('Conflito entre aparelhos')).toBeUndefined()})
 it('aceita zero observado, decimal com vírgula e ausência, rejeita contagem decimal',()=>{expect(validarCampos({vivos:'0',natimortos:'',comprimento:'42,5',latitude:'-8,12',longitude:'-34,9',datum:'WGS84'})).toEqual({});expect(validarCampos({vivos:'1.5'}).vivos).toContain('inteira')})
 it('ao escolher sem transferência, ignora destino abandonado; protege IDs e autoria na correção',()=>{
  expect(validarCadastro({tipo:'CD',natureza:'REPRODUTIVO',situacao:'I','destino-latitude':'999',ovosTransferencia:'errado'})).toEqual({});
  const e=criar(),o=e.ocorrencias[0]!,n=corrigirCadastro(e,o.id,{...o,id:'outro',projetoId:'outro',ninhoId:null,criadoPor:'intruso'} as CorrecaoCadastro,'Erro de preenchimento',m());
  expect(n.ocorrencias[0]).toMatchObject({id:o.id,projetoId:o.projetoId,ninhoId:o.ninhoId,criadoPor:o.criadoPor});
 })
 it('corrige origem/data/registro preservando pré-imagem, versões e reserva anterior',()=>{const e=criar(),o=e.ocorrencias[0]!;const campos:CorrecaoCadastro={...o,numeroRegistro:'0008',dataOcorrencia:'2026-10-01',noiteReferencia:'2026-10-01',localOrigem:{...o.localOrigem,latitude:-8.12}};const n=corrigirCadastro(e,o.id,campos,'Latitude e número digitados incorretamente',m());expect(e.ocorrencias[0]!.localOrigem.latitude).toBe(o.localOrigem.latitude);expect(n.ocorrencias[0]!.numeroRegistro).toBe('0008');expect(n.operacoes.at(-1)!.anterior).toMatchObject({ocorrencia:{numeroRegistro:'007',localOrigem:o.localOrigem}});const p=prepararGravacao(e,n);expect(p.motivo).toContain('incorretamente');expect(p.reservas[0]!.dados.numero).toBe('0008');expect(p.projecoes[0]!.dados.datas.OCORR).toBe('2026-10-01')})
 it('não permite usar correção para manter ninho sem desova nem remover autoria',()=>{const e=criar(),o=e.ocorrencias[0]!;expect(()=>corrigirCadastro(e,o.id,{...o,tipoOcorrencia:'ML'},'Erro',m())).toThrow('CD');expect(()=>corrigirCadastro(e,o.id,o,'',m())).toThrow('Motivo');expect(()=>corrigirCadastro({...e,contexto:{...e.contexto!,papel:'consulta'}},o.id,o,'Erro',m())).toThrow('consulta')})
 it('transferência posterior mantém origem; correção da transferência não duplica histórico',()=>{const e=criar(),id=e.ninhos[0]!.id;const a=registrarTransferencia(e,{...transferenciaBase,ninhoId:id,destino:'PRAIA',numeroNinhoCercado:null,localDestino:{...transferenciaBase.localDestino,praiaCodigo:'001',localKm:'8'}},m());const t=a.transferencias[0]!;const b=registrarTransferencia(a,{...t,ovosTransferencia:0,localDestino:{...t.localDestino,localKm:'9'}},m(),t.id,'Quantidade e trecho errados');expect(b.transferencias).toHaveLength(1);expect(b.transferencias[0]!.ovosTransferencia).toBe(0);expect(b.transferencias[0]!.versao).toBe(2);const ficha=montarFichaNinho({ninho:b.ninhos[0]!,ocorrencia:b.ocorrencias[0]!,transferencias:b.transferencias,aberturas:[]});expect(ficha.posicaoAtual.local.localKm).toBe('9');expect(b.ocorrencias[0]!.localOrigem).toEqual(e.ocorrencias[0]!.localOrigem)})
 it('exclusão de treino remove somente o ninho escolhido e mantém a pré-imagem',()=>{const e=criarTreino(),id=e.ninhos[0]!.id;const n=excluirNinhoTreino(e,id,'Duplicado fictício',m());expect(n.ninhos).toHaveLength(e.ninhos.length-1);expect(n.operacoes.at(-1)!.anterior).toMatchObject({ninho:{id}});expect(()=>excluirNinhoTreino(criar(),id,'Erro',m())).toThrow('coordenação')})
})
