import {camposExportacao,type RegistroRelatorio} from './relatorio'
import type {Localizacao} from '../domain/tipos'
export type LinhaCampo=[string,string]
export interface SecaoPDF {titulo:string;linhas:LinhaCampo[]}
export const ROTULOS:Record<string,string>={N_REGISTRO:'Número de registro',ESPECIE:'Espécie',DATA_OCORR:'Data da ocorrência',LATITUDE:'Latitude original (graus)',LONGITUDE:'Longitude original (graus)',DATUM:'Sistema de coordenadas',BAIRRO:'Bairro',LOCAL_ENDERECO:'Local / referência',HORA_OCORR:'Hora da ocorrência',PRAIA:'Código da praia original',LOCAL_KM:'Trecho original (km)',TIPO_OCORR:'Tipo de ocorrência',OBS:'Observações da ocorrência',MARCAS_ENC:'Marcas encontradas',MARCAS_COL:'Marcas colocadas',MARCAS_RET:'Marcas retiradas',COMP_CASCO:'Comprimento do casco (cm)',LARG_CASCO:'Largura do casco (cm)',TUMORES:'Presença de tumores',COLETA_MATERIAL_BIOLOGICO:'Material biológico coletado',EVIDENCIA_INT_PESCA:'Evidência de interação com pesca',TIPO_EVIDENCIA:'Tipo de evidência',SITUACAO:'Situação de conservação',TEMP_TRANSF:'Tempo entre postura e transferência',OVOS_TRANS:'Ovos observados na transferência',OVOS_FURAD:'Ovos furados',NAO_VIAVEIS:'Ovos não viáveis (D. coriacea)',N_NINHO:'Número dentro do cercado',PRAIA_DEST_P:'Código da praia de destino',LOCAL_KM_P:'Trecho de destino (km)',DATA_ECLOS:'Data da eclosão',DATA_ABERT:'Data da abertura',HIST_NINHO:'Histórico do ninho',VIVOS:'Filhotes vivos',NATIMORTOS:'Filhotes natimortos',OVOS_N_ECL:'Ovos não eclodidos',OVOS_TOT:'Total de ovos (calculado)',PCT_VIVOS:'Filhotes vivos (%)',TEMP_INCUB:'Tempo de incubação (dias)',PALAVRAS_CHAVE:'Palavras-chave',VERSAO_FORMULA:'Versão da fórmula'}
const CODIGOS:Record<string,Record<string,string>>={ESPECIE:{CC:'Caretta caretta',EI:'Eretmochelys imbricata',LO:'Lepidochelys olivacea',CM:'Chelonia mydas',DC:'Dermochelys coriacea',NI:'Não identificada'},TIPO_OCORR:{CD:'Com desova',ML:'Meia lua',SD:'Sem desova',ND:'Não determinado',PI:'Processo de desova interrompido'},SITUACAO:{I:'No local original (in situ)',T:'Transferido para cercado',P:'Transferido para praia'},TEMP_TRANSF:{A:'Até 6 horas após a postura',B:'6 a 12 horas; sem hora da postura, até 09:00',C:'12 a 24 horas; sem hora da postura, após 09:00',D:'Mais de 24 horas após a postura',E:'Mais de 15 dias após a postura'},TUMORES:{S:'Sim',N:'Não',I:'Indeterminado (não examinada)'},HIST_NINHO:{PH:'Predação humana',PA:'Predação por animais',PM:'Perdido pela ação da maré',PE:'Perdido pela retirada das estacas',SU:'Ninho com sucesso de incubação',NM:'Acompanhamento não realizado por decisão da equipe',OT:'Outras interferências (ver observações)'}}
export function legivel(v:unknown):string {if(v===null||v===undefined||v==='')return 'Não informado';if(typeof v==='boolean')return v?'Sim':'Não';if(Array.isArray(v))return v.length?v.map(legivel).join(', '):'Nenhum registrado';return String(v)}
export function dataLegivel(v:string|null|undefined):string{return v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v.slice(8)+'/'+v.slice(5,7)+'/'+v.slice(0,4):legivel(v)}
export function valorCampo(k:string,v:unknown):string {if(v==null)return 'Não informado';const texto=legivel(v);if(CODIGOS[k]?.[texto])return CODIGOS[k]![texto]+' ('+texto+')';if(k.startsWith('DATA_'))return dataLegivel(String(v));if(['LATITUDE','LONGITUDE'].includes(k)&&typeof v==='number')return v.toFixed(7);return texto}
export function motivoLegivel(s:string):string {return s.replace(/HIST_NINHO = SU/g,'histórico de sucesso de incubação (SU)').replace(/TIPO_OCORR = CD/g,'ocorrência com desova (CD)').replace(/OVOS_TOT/g,'total de ovos').replace(/PCT_VIVOS/g,'percentual de filhotes vivos').replace(/TEMP_INCUB/g,'tempo de incubação').replace(/DATA_OCORR/g,'data da ocorrência').replace(/DATA_ECLOS/g,'data da eclosão').replace(/VIVOS/g,'filhotes vivos')}
export function localLegivel(l:Localizacao):LinhaCampo[] {return [['Código da praia',legivel(l.praiaCodigo)],['Trecho (km)',legivel(l.localKm)],['Bairro',legivel(l.bairro)],['Local / referência',legivel(l.referencia)],['Latitude (graus)',l.latitude===null?'Não informado':l.latitude.toFixed(7)],['Longitude (graus)',l.longitude===null?'Não informado':l.longitude.toFixed(7)],['Sistema de coordenadas (datum)',legivel(l.datum)],['Margem de erro do GPS',l.precisaoGpsM===null?'Não informada':legivel(l.precisaoGpsM)+' m'],['Origem das coordenadas',l.fonteGps==='dispositivo'?'GPS do dispositivo':l.fonteGps==='manual'?'Digitadas manualmente':'Não informada'],['Momento da captura GPS',legivel(l.capturadoEm)]]}
export function secoesFicha(r:RegistroRelatorio,nomes:Record<string,string>={}):SecaoPDF[] {
 const campos=camposExportacao(r),o=r.origem.ocorrencia!,f=r.ficha
 const autor=(id:string|null)=>id&&nomes[id]?nomes[id]!:'Nome não informado; autoria preservada no JSON'
 const linha=(k:string):LinhaCampo=>{let v=valorCampo(k,campos[k as keyof typeof campos]);if(k==='NAO_VIAVEIS'&&o.especieCodigo!=='DC')v='Não aplicável: exclusivo de D. coriacea';if(k==='N_NINHO'&&f.ninho.situacao!=='T')v='Não aplicável: ninho fora de cercado';if(['PRAIA_DEST_P','LOCAL_KM_P'].includes(k)&&f.ninho.situacao!=='P')v='Não aplicável: sem transferência atual para praia';if(k==='HORA_OCORR'&&o.flagrante!==true)v='Não aplicável: sem flagrante registrado';if(k==='TEMP_TRANSF'&&!f.transferenciasOrdenadas.length)v='Não aplicável: sem transferência';if(campos[k as keyof typeof campos]==null&&['PCT_VIVOS','TEMP_INCUB','OVOS_TOT'].includes(k)){const motivo=r.linha.motivos.find(m=>m.startsWith(k+':'));if(motivo)v='Não calculado: '+motivoLegivel(motivo.slice(k.length+1).trim())}return [ROTULOS[k]+' ('+k+')',v]}
 const grupos:[string,string[]][]=[['Identificação e ocorrência',['N_REGISTRO','TIPO_OCORR','DATA_OCORR','HORA_OCORR','ESPECIE']],['Localização original',['PRAIA','LOCAL_KM','BAIRRO','LOCAL_ENDERECO','LATITUDE','LONGITUDE','DATUM']],['Tartaruga e coleta',['MARCAS_ENC','MARCAS_COL','MARCAS_RET','COMP_CASCO','LARG_CASCO','TUMORES','COLETA_MATERIAL_BIOLOGICO','EVIDENCIA_INT_PESCA','TIPO_EVIDENCIA','PALAVRAS_CHAVE']],['Conservação e resultado',['SITUACAO','HIST_NINHO','TEMP_TRANSF','OVOS_TRANS','N_NINHO','PRAIA_DEST_P','LOCAL_KM_P']],['Eclosão, abertura e contagens',['DATA_ECLOS','DATA_ABERT','VIVOS','NATIMORTOS','OVOS_N_ECL','OVOS_FURAD','NAO_VIAVEIS','OVOS_TOT','PCT_VIVOS','TEMP_INCUB','VERSAO_FORMULA']],['Observações',['OBS']]]
 const secoes=grupos.map(([titulo,ks])=>({titulo,linhas:ks.map(linha)}))
 secoes[0]!.linhas.push(['Código interno do ninho',f.ninho.codigoInterno],['Temporada',legivel(o.temporadaId)],['Responsável pela ocorrência',autor(o.responsavelId)],['Flagrante da tartaruga',legivel(o.flagrante)],['Verificação da praia realizada',legivel(o.verificacaoPraiaRealizada)],['Problema na incubação (acréscimo do projeto)',legivel(f.ninho.problemaIncubacao)])
 secoes.push({titulo:'Metadados do GPS original',linhas:localLegivel(o.localOrigem).slice(7)},{titulo:'Localização atual (derivada do histórico)',linhas:localLegivel(f.posicaoAtual.local)})
 for(const [i,t] of f.transferenciasOrdenadas.entries())secoes.push({titulo:'Transferência '+(i+1),linhas:[['Data da transferência',dataLegivel(t.dataTransferencia)],['Instante registrado',legivel(t.instanteTransferencia)],['Destino',t.destino==='CERCADO'?'Cercado de incubação':'Praia'],['Tempo de transferência',valorCampo('TEMP_TRANSF',t.tempoTransferencia)],['Ovos observados',legivel(t.ovosTransferencia)],['Identificador do cercado',t.destino==='CERCADO'?legivel(t.cercadoId):'Não aplicável'],['Número dentro do cercado',t.destino==='CERCADO'?legivel(t.numeroNinhoCercado):'Não aplicável'],...localLegivel(t.localDestino),['Responsável',autor(t.responsavelId)],['Observações',legivel(t.observacoes)]]})
 if(!f.transferenciasOrdenadas.length)secoes.push({titulo:'Transferências',linhas:[['Registros','Nenhuma transferência registrada']]})
 for(const [i,v] of (r.origem.visitas??[]).entries())secoes.push({titulo:'Visita '+(i+1)+' (acréscimo do projeto)',linhas:[['Data',dataLegivel(v.dataVisita)],['Responsável',autor(v.responsavelId)],['Condição observada',legivel(v.condicao)],['Eventos',v.eventos.length?v.eventos.map(e=>({predacao:'Predação',mare:'Maré',perda_marcacao:'Perda da marcação',outro:'Outro'}[e])).join(', '):'Nenhum registrado'],['Observações',legivel(v.observacoes)]]})
 for(const [i,a] of r.origem.aberturas.entries())secoes.push({titulo:'Registro de eclosão / abertura '+(i+1),linhas:[['Data da eclosão',dataLegivel(a.dataEclosao)],['Noite de referência da eclosão',dataLegivel(a.noiteReferenciaEclosao)],['Data da abertura',dataLegivel(a.dataAbertura)],['Noite de referência da abertura',dataLegivel(a.noiteReferenciaAbertura)],['Instante registrado da eclosão',legivel(a.instanteEclosao)],['Instante registrado da abertura',legivel(a.instanteAbertura)],['Primeiro filhote (hora)',legivel(a.horaPrimeiroFilhote)],['Último filhote (hora)',legivel(a.horaUltimoFilhote)],['Filhotes vivos',legivel(a.vivos)],['Filhotes natimortos',legivel(a.natimortos)],['Ovos não eclodidos',legivel(a.ovosNaoEclodidos)],['Ovos furados',legivel(a.ovosFurados)],['Ovos não viáveis',o.especieCodigo==='DC'?legivel(a.naoViaveis):'Não aplicável: exclusivo de D. coriacea'],['Responsável',autor(a.responsavelId)],['Observações',legivel(a.observacoes)]].filter(([k])=>r.origem.aberturas.length>1||!['Data da eclosão','Data da abertura','Filhotes vivos','Filhotes natimortos','Ovos não eclodidos','Ovos furados','Ovos não viáveis'].includes(k!)) as LinhaCampo[]})
 const extras=r.linha.motivos.filter(m=>!['PCT_VIVOS:','TEMP_INCUB:','OVOS_TOT:'].some(k=>m.startsWith(k)));if(extras.length)secoes.push({titulo:'Conferência de dados',linhas:extras.map(m=>['Conferir',motivoLegivel(m)] as LinhaCampo)})
 return secoes
}
