import {expect,it} from 'vitest'
import {alertaPrevisao,aplicarAno,indicadorArmazenamento,validarEntradaGestao,type GestaoNinho} from '../../src/domain/gestao'
import {montarRelatorio} from '../../src/report/relatorio'
import {dadosDemonstracao} from '../../src/report/exemplos'
const r=()=>montarRelatorio({projetoNome:'Fictício',dados:dadosDemonstracao(),consulta:{projetoId:'projeto-demo',todos:true,criterio:'OCORR',inicio:'2026-01-01',fim:'2026-12-31'},fonte:{demonstracao:true,online:false,sincronizacaoConfirmada:false,conjuntoCompleto:true},geradoEm:'2026-10-03T12:00:00Z'})
const g=(id:string,ano=2026):GestaoNinho=>({id,projeto_id:'projeto-demo',ano,numero:'001',previsao_eclosao:'2026-10-10',antecedencia_dias:7,nota_previsao:'Equipe fictícia informou a data',versao:1,operacao_id:'op',atualizado_por:'teste',confirmado_em:null})
it('ano explícito separa registros de anos distintos e não elimina os sem ano do acesso',()=>{const rel=r(),[a,b]=rel.registros,gestao={[a!.ficha.ninho.id]:g(a!.ficha.ninho.id),[b!.ficha.ninho.id]:g(b!.ficha.ninho.id,2027)};expect(aplicarAno(rel,gestao,'2026',true).registros.map(n=>n.ficha.ninho.id)).toEqual([a!.ficha.ninho.id]);expect(aplicarAno(rel,gestao,'2027',true).registros).toHaveLength(1);expect(aplicarAno(rel,gestao,'sem-ano',false).registros).toHaveLength(rel.registros.length-2);expect(aplicarAno(rel,gestao,'todos',false).parcial).toBe(true);expect(rel.registros).toHaveLength(5)})
it('alerta usa previsão informada e antecedência; encerra após observação de eclosão/abertura',()=>{const n=r().registros[0]!,m=g(n.ficha.ninho.id);n.origem.aberturas=[];expect(alertaPrevisao(n,undefined,'2026-10-03')).toBeNull();expect(alertaPrevisao(n,m,'2026-10-02')).toBeNull();expect(alertaPrevisao(n,m,'2026-10-03')?.dias).toBe(7);expect(alertaPrevisao(n,m,'2026-10-10')?.dias).toBe(0);expect(alertaPrevisao(n,m,'2026-10-11')?.dias).toBe(-1);m.previsao_eclosao=null;expect(alertaPrevisao(n,m,'2026-10-11')).toBeNull();const comAbertura=r().registros.find(n=>n.origem.aberturas.some(a=>a.dataAbertura||a.dataEclosao))!;expect(alertaPrevisao(comAbertura,g(comAbertura.ficha.ninho.id),'2026-10-03')).toBeNull()})
it('não aceita previsão sem origem, data inválida ou número zero e preserva 001',()=>{expect(()=>validarEntradaGestao(g('n'))).not.toThrow();expect(()=>validarEntradaGestao({...g('n'),numero:'000'})).toThrow();expect(()=>validarEntradaGestao({...g('n'),previsao_eclosao:'2026-02-30'})).toThrow();expect(()=>validarEntradaGestao({...g('n'),nota_previsao:null})).toThrow();expect(()=>validarEntradaGestao({...g('n'),numero:''})).not.toThrow();expect(()=>validarEntradaGestao({...g('n'),numero:'0001'})).toThrow()})
it('armazenamento desconhecido não vira zero; alerta depende de medição explícita',()=>{expect(indicadorArmazenamento(null).percentual).toBeNull();expect(indicadorArmazenamento({projeto_id:'p',uso_mib:820,medido_em:'2026-10-03',versao:1,atualizado_por:'c',confirmado_em:null}).pertoLimite).toBe(true)})
