// Protótipo visual. Dados FICTÍCIOS. Nada é salvo; sem Firebase.
const NAV=[['ninhos','Ninhos'],['mapa','Mapa'],['ocorrencias','Ocorrências'],['relatorios','Relatórios'],['cadastros','Cadastros']];
const ic=n=>`<svg class="icone" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const NINHOS=[
{id:'FICT-N-001',reg:'0001',praia:'Praia Fictícia A',km:'km 2,4',sp:'Espécie exemplo 1',st:['info','Em acompanhamento','◔'],eclosao:null,vazios:true},
{id:'FICT-N-002',reg:'0002',praia:'Praia Fictícia B',km:'km 0,8',sp:'Não identificada',st:['ok','Aberto','✔'],eclosao:'2026-03-02',vivos:82,natimortos:0,naoEcl:6},
{id:'FICT-N-003',reg:'0003',praia:'Praia Fictícia A',km:'km 3,1',sp:'Espécie exemplo 2',st:['aviso','Dados incompletos','▲'],eclosao:'2026-03-10'}];
const VISITAS=[['2026-02-20 06:10','Responsável Fictício 1','Marcação intacta'],['2026-02-27 06:05','Responsável Fictício 1','Evento: ação da maré — areia removida']];
const selo=([t,x,i])=>`<span class="selo ${t}">${i} ${x}</span>`;
const campo=(l,t='text',aj='')=>`<div><label>${l}<input type="${t}"></label>${aj?`<small class="ajuda">${aj}</small>`:''}</div>`;
const sel=(l,o,id='')=>`<div><label>${l}<select ${id?`id="${id}"`:''}>${o.map(x=>`<option>${x}</option>`).join('')}</select></label></div>`;
const nao=m=>`<button class="btn" data-nao="${m}">`;
const ETAPAS=['1 Identificação','2 Ocorrência','3 Manejo','4 Acompanhamento','5 Eclosão'];
function etapa(i){return[
`<div class="grade">${campo('Código interno do ninho')}${campo('Nº do registro da ficha')}${campo('Projeto')}${campo('Temporada')}${campo('Responsável')}${campo('Praia')}${campo('Trecho / km')}${campo('Bairro')}${campo('Referência do local')}${campo('Latitude')}${campo('Longitude')}${campo('Precisão (m)','number')}</div>
${nao('Captura de GPS não implementada. Na versão real, pede permissão e mostra a precisão.')}${ic('mapa')} Capturar localização</button>
<div class="msg aviso">▲ GPS sem permissão: preencha latitude e longitude manualmente.</div>`,
`<div class="grade">${campo('Data da ocorrência','date')}${campo('Hora (se aplicável)','time')}${sel('Tipo de ocorrência',['Selecione','Desova','Ninho encontrado','Outro'])}${sel('Espécie',['Selecione','Espécie exemplo 1','Espécie exemplo 2','Não identificada'])}${sel('Tartaruga observada?',['Não informado','Não','Sim'],'obs')}</div>
<div id="animal" hidden><h2>Dados do animal</h2><div class="grade">${campo('Marcas encontradas')}${campo('Marcas colocadas')}${campo('Marcas retiradas')}${campo('Comprimento do casco (cm)','number')}${campo('Largura do casco (cm)','number')}${sel('Tumores',['Não informado','Não','Sim'])}${sel('Coleta de material biológico',['Não informado','Não','Sim'])}${sel('Interação com pesca',['Não informado','Não','Sim'])}</div></div>
<label>Observações<textarea rows="3"></textarea></label><p class="ajuda">Se a tartaruga não foi observada, medidas e marcas não são exigidas.</p>`,
`${sel('Situação do ninho',['Permaneceu no local original','Transferido para cercado','Transferido para outra área da praia'],'man')}
<div class="cartao" style="margin-top:16px"><b>Localização original (preservada):</b> Praia Fictícia A, km 2,4<br><b>Localização atual:</b> <span id="atual">igual à original</span><br>${nao('Histórico de transferências: nenhuma registrada neste exemplo.')}Ver histórico de transferências</button></div>
<div id="transf" hidden><div class="grade">${campo('Data/hora da transferência','datetime-local')}${sel('Categoria do tempo',['Selecione','Categoria A (a validar)','Categoria B (a validar)'])}${campo('Responsável')}${campo('Ovos transferidos','number')}${campo('Ovos furados','number')}<div id="cerc">${campo('Nº no cercado','number')}</div>${campo('Praia de destino')}${campo('Trecho de destino')}${campo('Latitude destino')}${campo('Longitude destino')}</div></div>`,
`<div class="cartao"><b>Condição atual:</b> ${selo(['info','Em acompanhamento','◔'])}</div>${nao('Adicionar visita não salva neste protótipo.')}+ Adicionar visita</button>
<h2>Histórico de visitas</h2>${VISITAS.map(v=>`<div class="linha"><b>${v[0]}</b> — ${v[1]}<br>${v[2]}</div>`).join('')}
<div class="grade">${sel('Registrar evento',['Selecione','Predação','Ação da maré','Perda da marcação'])}</div>`,
`<p class="ajuda">Campo vazio = não informado. Zero só vale se for digitado.</p><div class="grade">${campo('Data da eclosão','date')}${campo('Data da abertura','date')}${campo('Filhotes vivos','number','Vazio ≠ 0')}${campo('Natimortos','number')}${campo('Ovos não eclodidos','number')}${campo('Ovos furados','number')}${campo('Ovos não viáveis (se aplicável)','number')}${sel('Situação oficial I/T/P',['Não informado','I','T','P'])}</div>
<label>Histórico final do ninho (oficial)<textarea rows="2"></textarea></label><label>Observações finais<textarea rows="2"></textarea></label>
<div class="msg info">ℹ Cálculos derivados: aguardando fórmulas oficiais da equipe. Nenhuma fórmula foi inventada.</div>`][i]}
const TELAS={
ninhos:()=>`<h1>Ninhos</h1><button class="btn prim" data-nao="Novo ninho abre a ficha vazia; sem gravação aqui.">+ Novo ninho</button><div style="margin-top:16px">${NINHOS.map(n=>`<a class="cartao" href="#/ficha/${n.id}"><b>${n.id}</b> · ficha ${n.reg} ${selo(n.st)}<br>${n.praia}, ${n.km} · ${n.sp}</a>`).join('')}</div>`,
mapa:()=>`<h1>Mapa</h1><svg class="mapa" viewBox="0 0 400 240" role="img" aria-label="Mapa ilustrativo com 3 ninhos fictícios"><rect y="150" width="400" height="90" fill="#DCCBA5"/><path d="M0 150Q100 130 200 150T400 140" stroke="#0E5A6B" stroke-width="4" fill="none"/>${[[80,175,'1'],[200,190,'2'],[310,170,'3']].map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="14" fill="#0B3C49" stroke="#fff" stroke-width="3"/><text x="${p[0]}" y="${p[1]+5}" fill="#fff" text-anchor="middle" font-size="14">${p[2]}</text>`).join('')}</svg><div class="msg info">ℹ Mapa ilustrativo. Integrar Leaflet + OpenStreetMap, com marcadores numerados e lista equivalente em texto.</div>`,
ocorrencias:()=>`<h1>Ocorrências sem ninho</h1><p>Tartaruga subiu à praia sem desova. <b>Não cria ninho.</b></p><div class="cartao"><div class="grade">${campo('Data','date')}${campo('Hora','time')}${campo('Praia')}${campo('Trecho / km')}${sel('Espécie',['Não identificada','Espécie exemplo 1'])}${campo('Latitude')}${campo('Longitude')}</div><label>Observações<textarea rows="2"></textarea></label>${nao('Não grava neste protótipo.')}Salvar ocorrência</button></div><div class="cartao"><b>2026-03-04</b> · Praia Fictícia B, km 1,2 · ▲ Sem desova</div>`,
relatorios:()=>`<h1>Relatórios</h1><div class="cartao"><div class="grade">${campo('Data inicial','date')}${campo('Data final','date')}${sel('Critério do período',['Data da ocorrência','Data da eclosão','Data da abertura'])}${sel('Praia',['Todas','Praia Fictícia A','Praia Fictícia B'])}${sel('Espécie',['Todas','Espécie exemplo 1','Não identificada'])}${sel('Temporada',['Todas','2025/2026'])}</div></div>
<div class="duas"><div><h2>Resumo (fictício)</h2><div class="cartao">3 registros · 1 com dados incompletos<br>Filhotes vivos informados: 82 (1 registro sem valor)</div><div class="msg aviso">▲ Relatório com dados incompletos: FICT-N-003 sem contagem de filhotes. Campo vazio não é somado como zero.</div>
<h2>Prévia dos registros</h2><div class="tabela-rolagem"><table><tr><th>Ninho</th><th>Praia</th><th>Eclosão</th><th>Vivos</th></tr>${NINHOS.map(n=>`<tr><td>${n.id}</td><td>${n.praia}</td><td>${n.eclosao||'—'}</td><td>${n.vivos??'—'}</td></tr>`).join('')}</table></div>${nao('Geração de PDF não implementada (sugestão: window.print() com CSS @media print).')}Baixar PDF</button></div>
<div><h2>Proposta A4 (a validar pela equipe)</h2><div class="a4"><h3>Relatório de Monitoramento de Ninhos</h3>Projeto fictício · Período: 01/02–31/03/2026<br>Critério: data da eclosão<hr><b>Resumo</b>: 3 registros, 1 incompleto<hr><table><tr><th>Ninho</th><th>Praia</th><th>Vivos</th></tr><tr><td>N-001</td><td>A</td><td>—</td></tr><tr><td>N-002</td><td>B</td><td>82</td></tr></table><hr><i>Fichas detalhadas a partir da pág. 2 · Observações · Página 1 de 3</i></div></div></div>`,
cadastros:()=>`<h1>Cadastros</h1><div class="cartao">Projetos · Temporadas · Responsáveis · Praias · Espécies (listas fictícias)</div><h2>Estados da interface (exemplos)</h2>
<div class="msg info">◔ Carregando…<div class="sk"></div><div class="sk" style="width:60%"></div></div><div class="msg info">ℹ Nenhum ninho cadastrado. Toque em “Novo ninho”.</div><div class="msg erro">✖ Não foi possível carregar os dados. ${nao('Tentar de novo: simulação.')}Tentar novamente</button></div><div class="msg aviso">▲ GPS indisponível neste aparelho. Digite as coordenadas.</div><div class="msg aviso">▲ Sem internet. Os registros ficam no aparelho.</div><div class="msg info">⟳ 2 alterações pendentes de sincronização.</div><div class="msg ok">✔ Sincronização concluída.</div><div class="msg erro">⚠ Conflito de dados: a ficha foi alterada em outro aparelho. Escolha qual versão manter.</div><div class="msg aviso">▲ Relatório com dados incompletos (ver Relatórios).</div>`};
function render(){const [,rota,id]=location.hash.split('/');const app=document.getElementById('app');
document.querySelector('nav').innerHTML=NAV.map(([k,t])=>`<a href="#/${k}" ${(rota===k||(rota==='ficha'&&k==='ninhos')||(!rota&&k==='ninhos'))?'aria-current="page"':''}>${ic(k)}${t}</a>`).join('');
const av='<div class="aviso-proto">Protótipo com dados fictícios. Nada é salvo.</div>';
if(rota==='ficha'){app.innerHTML=`${av}<p><a href="#/ninhos">← Ninhos</a></p><h1>Ficha ${id}</h1><div class="abas" role="tablist">${ETAPAS.map((e,i)=>`<button role="tab" aria-selected="${i==0}" data-et="${i}">${e}</button>`).join('')}</div><div id="et" class="cartao"></div>`;
const m=i=>{document.getElementById('et').innerHTML=etapa(i);app.querySelectorAll('[data-et]').forEach(b=>b.setAttribute('aria-selected',b.dataset.et==i));
const o=document.getElementById('obs');if(o)o.onchange=()=>document.getElementById('animal').hidden=o.value!=='Sim';
const g=document.getElementById('man');if(g)g.onchange=()=>{document.getElementById('transf').hidden=g.selectedIndex===0;document.getElementById('cerc').hidden=g.selectedIndex!==1;document.getElementById('atual').textContent=g.selectedIndex?'destino informado abaixo':'igual à original'}};
app.querySelectorAll('[data-et]').forEach(b=>b.onclick=()=>m(+b.dataset.et));m(0)}
else app.innerHTML=av+(TELAS[rota]||TELAS.ninhos)();
document.querySelectorAll('[data-nao]').forEach(b=>b.onclick=()=>alert('Não implementado: '+b.dataset.nao))}
addEventListener('hashchange',render);render();
